#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes

i=0
j=0

while [ "$i" -lt 13 ]
 do
  echo Hour: $i
  while [ "$j" -lt 60 ]
   do
    echo $j
    j=$(($j+1))
  done;
 i=$(($i+1))
 done;
 exit 0;